name: gofmt Linting

on:
  push:
    branches:
      - master

jobs:
  goLint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Lint
        run: |
          gofmt -l -s -w .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'RoseLoverX: auto Linting'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: AmarnathCjd
          commit_user_email: 72609355+AmarnathCjd@users.noreply.github.com
          commit_author: AmarnathCjd <72609355+AmarnathCjd+@users.noreply.github.com>
