name: Go TL Parser

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
        - cron: '0 */6 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build & Run TL Parser
      run: cd ./internal/cmd/tlgen && go run .

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "TLParser: Layer Updated"
        commit_options: "--no-verify"
        repository: .
        commit_user_name: AmarnathCJD
        commit_user_email: 72609355+AmarnathCjd@users.noreply.github.com
        commit_author: AmarnathCJD <72609355+AmarnathCjd+@users.noreply.github.com>


